### PR TITLE
Bump proto-lens and http2-grpc-types

### PR DESCRIPTION
**Pull request by jonringer**
lens-labels was removed in proto-lens-0.5.0.0

### CODE REVIEW

**Comment by jonringer** [comment]
Also, used the warp-grpc-example to build against these changes and was still able to run the client. Although it would be nice to have some tests to validate i didn't ruin any internal consistency.

**Comment by lucasdicioccio** [comment]
Oh right!

Yeah if you have some skills in configuring CIs I'd enjoy some combination of client/server to have some end-to-end coverage of the small galaxy of libraries we need.

**Comment by jonringer** [comment]
made a softlink to the other repo with my changes `ln -s ../warp-grpc warp-grc`, and in the stack.yaml i just edit it to:

warp-grpc-example/stack.yaml
```
resolver: lts-13.17
packages:
- .
- warp-grpc
...
```

**Comment by lucasdicioccio** [comment]
I use a very similar setup locally with a `stack-dev.yaml` file and I use STACK_YAML=stack-dev.yaml before building.

Maybe I can make a repo that uses submodules (or git fetch) to pull all the repositories and run stuff (I have some benchmark code that can serve as a cheap end-to-end test but I'd like to test against an official implementation).

**Pull request merged**
